# Generated by Django 5.1.6 on 2025-02-09 08:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_bookmaker_odds_oddshistory_oddstype_oddsvalue_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_birth_date_past',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z-]{2,10}$')]),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lt', datetime.datetime(2025, 2, 9, 8, 43, 32, 102897, tzinfo=datetime.timezone.utc))), name='coach_birth_date_past'),
        ),
    ]
