# Generated by Django 5.1.6 on 2025-02-09 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_remove_coach_coach_birth_date_past_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_birth_date_past',
        ),
        migrations.RemoveConstraint(
            model_name='coachcareer',
            name='career_end_date_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='playerinjury',
            name='injury_end_date_after_start',
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lt', datetime.datetime(2025, 2, 9, 8, 49, 11, 550799, tzinfo=datetime.timezone.utc))), name='coach_birth_date_past'),
        ),
        migrations.AddConstraint(
            model_name='coachcareer',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='career_end_date_after_start'),
        ),
        migrations.AddConstraint(
            model_name='playerinjury',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='injury_end_date_after_start'),
        ),
    ]
