# Generated by Django 5.1.6 on 2025-02-11 07:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_remove_coach_coach_birth_date_past_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixturestatistic',
            options={'ordering': ['fixture', 'team', 'stat_type']},
        ),
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_birth_date_past',
        ),
        migrations.AlterField(
            model_name='fixturestatistic',
            name='stat_type',
            field=models.CharField(choices=[('shots_on_goal', 'Shots on Goal'), ('shots_off_goal', 'Shots off Goal'), ('shots_insidebox', 'Shots insidebox'), ('shots_outsidebox', 'Shots outsidebox'), ('total_shots', 'Total Shots'), ('blocked_shots', 'Blocked Shots'), ('fouls', 'Fouls'), ('corner_kicks', 'Corner Kicks'), ('offsides', 'Offsides'), ('ball_possession', 'Ball Possession'), ('yellow_cards', 'Yellow Cards'), ('red_cards', 'Red Cards'), ('goalkeeper_saves', 'Goalkeeper Saves'), ('total_passes', 'Total passes'), ('passes_accurate', 'Passes accurate'), ('passes_percentage', 'Passes %')], help_text='Type of statistic from API-Football', max_length=50),
        ),
        migrations.AlterField(
            model_name='fixturestatistic',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Statistical value (percentages are stored as decimals)', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lt', datetime.datetime(2025, 2, 11, 7, 2, 36, 272212, tzinfo=datetime.timezone.utc))), name='coach_birth_date_past'),
        ),
    ]
