# Generated by Django 5.1.6 on 2025-02-11 11:14

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_alter_fixturestatistic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_by', models.CharField(default='manual', max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d-\\d-\\d(-\\d)?$')])),
                ('player_primary_color', models.CharField(blank=True, max_length=6, null=True)),
                ('player_number_color', models.CharField(blank=True, max_length=6, null=True)),
                ('player_border_color', models.CharField(blank=True, max_length=6, null=True)),
                ('goalkeeper_primary_color', models.CharField(blank=True, max_length=6, null=True)),
                ('goalkeeper_number_color', models.CharField(blank=True, max_length=6, null=True)),
                ('goalkeeper_border_color', models.CharField(blank=True, max_length=6, null=True)),
                ('update_by', models.CharField(default='manual', max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureLineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('F', 'Forward')], max_length=1)),
                ('grid', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d:\\d$')])),
                ('is_substitute', models.BooleanField(default=False)),
                ('update_by', models.CharField(default='manual', max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_birth_date_past',
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lt', datetime.datetime(2025, 2, 11, 11, 14, 8, 519727, tzinfo=datetime.timezone.utc))), name='coach_birth_date_past'),
        ),
        migrations.AddField(
            model_name='fixturecoach',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.coach'),
        ),
        migrations.AddField(
            model_name='fixturecoach',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.fixture'),
        ),
        migrations.AddField(
            model_name='fixturecoach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team'),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.fixture'),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team'),
        ),
        migrations.AddField(
            model_name='fixturelineupplayer',
            name='lineup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.fixturelineup'),
        ),
        migrations.AddField(
            model_name='fixturelineupplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player'),
        ),
        migrations.AddIndex(
            model_name='fixturecoach',
            index=models.Index(fields=['fixture', 'team'], name='football_fi_fixture_dd0dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixturecoach',
            constraint=models.UniqueConstraint(fields=('fixture', 'team'), name='unique_fixture_team_coach'),
        ),
        migrations.AddIndex(
            model_name='fixturelineup',
            index=models.Index(fields=['fixture', 'team'], name='football_fi_fixture_3e7ba3_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixturelineup',
            constraint=models.UniqueConstraint(fields=('fixture', 'team'), name='unique_fixture_team_lineup'),
        ),
        migrations.AddIndex(
            model_name='fixturelineupplayer',
            index=models.Index(fields=['lineup', 'player'], name='football_fi_lineup__7d20ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturelineupplayer',
            index=models.Index(fields=['lineup', 'position'], name='football_fi_lineup__748f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturelineupplayer',
            index=models.Index(fields=['is_substitute'], name='football_fi_is_subs_39a26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixturelineupplayer',
            constraint=models.UniqueConstraint(fields=('lineup', 'player'), name='unique_lineup_player'),
        ),
        migrations.AddConstraint(
            model_name='fixturelineupplayer',
            constraint=models.UniqueConstraint(fields=('lineup', 'number'), name='unique_lineup_number'),
        ),
        migrations.AddConstraint(
            model_name='fixturelineupplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('grid__isnull', False)), fields=('lineup', 'grid'), name='unique_lineup_grid'),
        ),
    ]
