# Generated by Django 5.1.6 on 2025-02-11 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_remove_coach_coach_birth_date_past_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_birth_date_past',
        ),
        migrations.AlterField(
            model_name='fixturestatistic',
            name='stat_type',
            field=models.CharField(choices=[('shots_on_goal', 'Shots on Goal'), ('shots_off_goal', 'Shots off Goal'), ('shots_insidebox', 'Shots insidebox'), ('shots_outsidebox', 'Shots outsidebox'), ('total_shots', 'Total Shots'), ('blocked_shots', 'Blocked Shots'), ('fouls', 'Fouls'), ('corner_kicks', 'Corner Kicks'), ('offsides', 'Offsides'), ('ball_possession', 'Ball Possession'), ('yellow_cards', 'Yellow Cards'), ('red_cards', 'Red Cards'), ('goalkeeper_saves', 'Goalkeeper Saves'), ('total_passes', 'Total passes'), ('passes_accurate', 'Passes accurate'), ('passes_percentage', 'Passes %'), ('goals_prevented', 'goals_prevented')], help_text='Type of statistic from API-Football', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lt', datetime.datetime(2025, 2, 11, 17, 51, 25, 243931, tzinfo=datetime.timezone.utc))), name='coach_birth_date_past'),
        ),
    ]
