# Generated by Django 5.1.6 on 2025-02-18 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_question_questiontheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_birth_date_past',
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lt', datetime.datetime(2025, 2, 18, 4, 34, 50, 258725, tzinfo=datetime.timezone.utc))), name='coach_birth_date_past'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTheme',
        ),
    ]
